### ISSUE TITLE
Unable to run the enforcer via command line

### ISSUE THREAD

**Issue by Klaus-Nji-sp** [byu-oit/openapi-enforcer#87]
Not sure if I am missing this in the document but is there a way to run the enforcer via command line?

This is what we had to do:

```
const Enforcer = require('openapi-enforcer')
// JSON and YAML files accepted
Enforcer('/api.beta.yaml', { fullResult: true })
    .then(function ({ error, warning }) {
        if (!error) {
            console.log('No errors with your document')
            if (warning) console.warn(warning)
        } else {
            console.error(error)
        }
    })
```

To run this from a command line.  However, it will have been nice to just issue a one liner to get this running as well.

**Comment by Gi60s** [comment]
There is a CLI. although it's not as fleshed out as I'd like it to be, it does work.

https://www.npmjs.com/package/openapi-enforcer-cli

Let me know if it doesn't do what you're looking for.

**Comment by Klaus-Nji-sp** [comment]
Thanks again for the quick response.

**Comment by nikhil-nair-sp** [comment]
The output of validating a document with the tool vs the above script is that it's much more terse and losing a lot of information. We'd like to have the same level of verbosity as validating with `fullResult: true` via the shell.

**Comment by Gi60s** [comment]
I think that is an option with the cli. 

1. Install the CLI:  `npm install -g openapi-enforcer-cli`
2. Run the command: `openapi-enforcer validate api.beta.yaml`

If that doesn't do the trick, let me know.

**Comment by nikhil-nair-sp** [comment]
Right, I ran it before, but it wasn't giving us all the information compared to running the above script (where it pulls the latest `openapi-enforcer`). Looking at package.lock of `openapi-enforcer-cli`, it uses 1.10.0 of `openapi-enforcer`, so it might be out of date. Maybe we could close this issue and open a new one in the other repo?

**Comment by Gi60s** [comment]
That might be the problem. I've updated the dependencies and removed the lock file which should allow the dependencies to update independent of the CLI.

I've published it to NPM as version `0.3.1`. Try it out and let me know if that worked.

**Comment by nikhil-nair-sp** [comment]
Still having the same issue where we are getting less warnings with the cli than my script.
output from the cli:
```

Cannot read property 'hasOwnProperty' of null
```

whereas the output of my script returns 179 lines of errors, and they are legitimate, for example, one snippet of a warning looks like:
```
      at: /verified-from-addresses/{id} > delete > responses > 204
        A 204 response must not contain a body (https://tools.ietf.org/html/rfc7231#section-6.3.5) but this response has a defined content. [WRES003]
      at: /sod-policies > post > responses > 201
        A 201 response for a POST request should return a location header (https://tools.ietf.org/html/rfc7231#section-4.3.3) and this is not documented in your OpenAPI document. [WRES001] ]
```

And it might not be a great idea to remove a package-lock.json on an executable which end users use, since future updated dependencies may break the cli, but that's just my opinion.

**Comment by Gi60s** [comment]
You might be right about disabling the package lock. I've never tried doing that before, but it could allow people to update the version of the enforcer without updates to the CLI as well. Going to have to consider that one a little bit more.

I'm going to take a closer look at the CLI validator. I thought the code is very similar to what you had posted, but I'll do a more thorough comparison.

**Comment by Gi60s** [comment]
This one has me a bit stumped so here is what I've done:

1. I rewrote the validate code to look more like what you've provided.
2. I added to the version command `openapi-enforcer version` that it will also output the version of the enforcer that it's using.
3. I re-enabled the package log.
4. I published this to NPM as version `0.3.2`.

Here is the validator code:

```js
'use strict'
const Enforcer = require('openapi-enforcer')
const path = require('path')

module.exports = function (program) {
  program
    .command('validate <oas-doc>')
    .description('Validate an Open API Specification document')
    .option('-c, --clean-exit', 'If the OpenAPI document is not valid, do not throw an exception.')
    .action((oasDoc, command) => {
      const fullPath = path.resolve(process.cwd(), oasDoc)
      Enforcer(fullPath, { fullResult: true })
        .then(({ error, warning }) => {
          if (!error) {
            console.log('Document is valid')
            if (warning) console.warn(warning)
          } else {
            console.error(error)
          }

          if (!command.cleanExit && error) process.exit(1)
        })
        .catch(err => {
          console.log(err.message)
          if (!command.cleanExit) process.exit(1)
        })
    })
}
```

Let me know if it works. If it doesn't maybe share the YAML file that you're using with me and I'll do some deep code debugging.

**Comment by nikhil-nair-sp** [comment]
Getting the same output from the cli before, now with the first newline removed. We'll ask the right channels to figure out if we are able to share the API spec before we do so.

**Comment by Gi60s** [comment]
Good news. I've identified the problem as to why you're seeing the `Cannot read property 'hasOwnProperty' of null` message in the CLI.  I've already identified the fix and will work on getting this published soon.

**Comment by Gi60s** [comment]
OK. Try out the latest version of the `openapi-enforcer-cli`, version `0.3.3`.

**Comment by nikhil-nair-sp** [comment]
looks like we caught some real errors in our docs (thanks you!). We'll come back once we fix those and see if we are still having issues with the warnings not being displayed.

**Comment by Gi60s** [comment]
Sounds great. Thanks for your help working through this error. You've made this library better still than it was.

I'll close this ticket for now. If we need to we can create a new one or re-open later.

**Comment by Klaus-Nji-sp** [comment]
@Gi60s thanks for being over so prompt in responding to issues.  Certainly appreciate your efforts on this great library.
